_wandb:
    value:
        cli_version: 0.24.0
        e:
            4cegfwzdwtkiq94x41bnhi4mx42okk0p:
                codePath: GNN/train_gnn.py
                codePathLocal: train_gnn.py
                cpu_count: 28
                cpu_count_logical: 28
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "62847451136"
                        used: "7206957056"
                email: erichabjan@gmail.com
                executable: /home/habjan.e/miniconda3/envs/cl_dyn/bin/python3
                git:
                    commit: 000957dab97d1c1fa542ee3849a774747bf1ffa9
                    remote: git@github.com:erichabjan/TNG_cluster_dynamics.git
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-ca3fb61b-45d1-3155-edc8-fc634181f58c
                host: d1020
                memory:
                    total: "200811167744"
                os: Linux-5.14.0-362.13.1.el9_3.x86_64-x86_64-with-glibc2.34
                program: /home/habjan.e/TNG/TNG_cluster_dynamics/GNN/train_gnn.py
                python: CPython 3.11.13
                root: /home/habjan.e/TNG/TNG_cluster_dynamics/GNN
                slurm:
                    cluster_name: explorer
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0555555
                    cpu_bind_list: "0x0555555"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "12"
                    cpus_per_task: "12"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: j.mccleary
                    job_cpus_per_node: "12"
                    job_end_time: "1769115500"
                    job_gid: "100"
                    job_group: users
                    job_id: "3891959"
                    job_name: bash
                    job_nodelist: d1020
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1769101100"
                    job_uid: "92311"
                    job_user: habjan.e
                    jobid: "3891959"
                    launch_node_ipaddr: 10.99.200.107
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: d1020
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "33295"
                    pty_win_col: "113"
                    pty_win_row: "27"
                    script_context: prolog_task
                    srun_comm_host: 10.99.200.107
                    srun_comm_port: "46341"
                    step_gpus: "1"
                    step_id: "0"
                    step_launcher_port: "46341"
                    step_nodelist: d1020
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/habjan.e/TNG/TNG_cluster_dynamics
                    submit_host: explorer-02
                    task_pid: "2185013"
                    tasks_per_node: "1"
                    topology_addr: d1020
                    topology_addr_pattern: node
                    tres_per_task: cpu:12
                    umask: "0022"
                startedAt: "2026-01-22T17:38:45.763152Z"
                writerId: 4cegfwzdwtkiq94x41bnhi4mx42okk0p
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: ConvGNN
epochs:
    value: 1000
learning_rate:
    value: 0.00030000000000000003
